<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../services/AssetStorage.Abstractions/AssetStorage.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="Markdig" />
  </ItemGroup>
</Project>
